# Generated by Django 6.0.4 on 2026-05-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="learning_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
