# Generated by Django 6.0.4 on 2026-04-30 09:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import lessons.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок",
                "verbose_name_plural": "Блоки",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="Слаг")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="ChoiceAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100, verbose_name="Ответ")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Верно"),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответов",
            },
        ),
        migrations.CreateModel(
            name="AudioBlock",
            fields=[
                (
                    "block_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="lessons.block",
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        upload_to="audioblocks/",
                        validators=[
                            lessons.validators.FileSizeValidator(50),
                            lessons.validators.UploadExtensionValidator(
                                {"aac", "m4a", "mp3", "ogg", "wav"}
                            ),
                        ],
                        verbose_name="Аудио",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аудио блок",
                "verbose_name_plural": "Аудио блоки",
            },
            bases=("lessons.block",),
        ),
        migrations.CreateModel(
            name="ChoiceQuestion",
            fields=[
                (
                    "block_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="lessons.block",
                    ),
                ),
                ("question", models.CharField(max_length=200, verbose_name="Вопрос")),
                (
                    "max_choices",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Максимум правильных вариантов",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Срок сдачи"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Максимум попыток",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос с выбором",
                "verbose_name_plural": "Вопросы с выбором",
            },
            bases=("lessons.block",),
        ),
        migrations.CreateModel(
            name="FileQuestion",
            fields=[
                (
                    "block_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="lessons.block",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Срок сдачи"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Максимум попыток",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос с файлом",
                "verbose_name_plural": "Вопросы с файлами",
            },
            bases=("lessons.block",),
        ),
        migrations.CreateModel(
            name="ImageBlock",
            fields=[
                (
                    "block_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="lessons.block",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/imageblocks/",
                        validators=[
                            lessons.validators.FileSizeValidator(10),
                            lessons.validators.UploadExtensionValidator(
                                {"jpeg", "jpg", "png", "webp"}
                            ),
                        ],
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото блок",
                "verbose_name_plural": "Фото блоки",
            },
            bases=("lessons.block",),
        ),
        migrations.CreateModel(
            name="TeacherFileBlock",
            fields=[
                (
                    "block_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="lessons.block",
                    ),
                ),
                (
                    "teachers_file",
                    models.FileField(
                        upload_to="teachers_files/",
                        validators=[
                            lessons.validators.FileSizeValidator(50),
                            lessons.validators.UploadExtensionValidator(
                                {
                                    "7z",
                                    "doc",
                                    "docx",
                                    "pdf",
                                    "ppt",
                                    "pptx",
                                    "rar",
                                    "txt",
                                    "xls",
                                    "xlsx",
                                    "zip",
                                }
                            ),
                        ],
                        verbose_name="Файл",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок файла учителя",
                "verbose_name_plural": "Блоки файла учителя",
            },
            bases=("lessons.block",),
        ),
        migrations.CreateModel(
            name="TextBlock",
            fields=[
                (
                    "block_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="lessons.block",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
            ],
            options={
                "verbose_name": "Текстовый блок",
                "verbose_name_plural": "Текстовые блоки",
            },
            bases=("lessons.block",),
        ),
        migrations.CreateModel(
            name="TextQuestion",
            fields=[
                (
                    "block_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="lessons.block",
                    ),
                ),
                ("question", models.CharField(max_length=200, verbose_name="Вопрос")),
                (
                    "correct_answer",
                    models.CharField(max_length=100, verbose_name="Правильный ответ"),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Срок сдачи"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Максимум попыток",
                    ),
                ),
            ],
            options={
                "verbose_name": "Текстовый вопрос",
                "verbose_name_plural": "Текстовые вопросы",
            },
            bases=("lessons.block",),
        ),
        migrations.CreateModel(
            name="VideoBlock",
            fields=[
                (
                    "block_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="lessons.block",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        upload_to="videoblocks/",
                        validators=[
                            lessons.validators.FileSizeValidator(200),
                            lessons.validators.UploadExtensionValidator(
                                {"m4v", "mov", "mp4", "webm"}
                            ),
                        ],
                        verbose_name="Видео",
                    ),
                ),
            ],
            options={
                "verbose_name": "Видео блок",
                "verbose_name_plural": "Видео блоки",
            },
            bases=("lessons.block",),
        ),
        migrations.CreateModel(
            name="ChoiceAnswerSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Выбрано"),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="lessons.choiceanswer",
                        verbose_name="Выбранный вариант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выбор варианта",
                "verbose_name_plural": "Выборы вариантов",
            },
        ),
        migrations.CreateModel(
            name="ChoiceAnswerSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Попытка",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Отправлено"
                    ),
                ),
                (
                    "selected",
                    models.ManyToManyField(
                        related_name="choice_submissions",
                        through="lessons.ChoiceAnswerSelection",
                        to="lessons.choiceanswer",
                        verbose_name="Выбрано",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choice_answer_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="lessons.choicequestion",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отправленный выбранный ответ",
                "verbose_name_plural": "Отправленные выбранные ответы",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddField(
            model_name="choiceanswerselection",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selections",
                to="lessons.choiceanswersubmission",
                verbose_name="Отправка",
            ),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/courses/", verbose_name="Изображение"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлен"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses_authored",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="lessons.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="lessons.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="block",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="lessons.lesson",
                verbose_name="Урок",
            ),
        ),
        migrations.AddField(
            model_name="choiceanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="lessons.choicequestion",
                verbose_name="Вопрос",
            ),
        ),
        migrations.CreateModel(
            name="FileAnswerSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="students_files/",
                        validators=[
                            lessons.validators.FileSizeValidator(50),
                            lessons.validators.UploadExtensionValidator(
                                {
                                    "7z",
                                    "doc",
                                    "docx",
                                    "jpeg",
                                    "jpg",
                                    "pdf",
                                    "png",
                                    "rar",
                                    "zip",
                                }
                            ),
                        ],
                        verbose_name="Файл",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "teacher_comment",
                    models.TextField(
                        blank=True, verbose_name="Комментарий преподавателя"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_answer_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="lessons.filequestion",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отправленный файл студента",
                "verbose_name_plural": "Отправленные файлы студента",
            },
        ),
        migrations.CreateModel(
            name="TextAnswerSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=100, verbose_name="Ответ")),
                (
                    "attempt",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Попытка",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Отправлено"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_answer_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="lessons.textquestion",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отправленный текстовый ответ",
                "verbose_name_plural": "Отправленные текстовые ответы",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="choiceanswerselection",
            index=models.Index(
                fields=["submission"], name="lessons_cho_submiss_78daa0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="choiceanswerselection",
            constraint=models.UniqueConstraint(
                fields=("submission", "answer"), name="unique_answer_per_submission"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["is_published", "created_at"],
                name="lessons_cou_is_publ_10f9ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["course", "order"], name="lessons_les_course__5adb2b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("course", "order"), name="unique_lesson_order_in_course"
            ),
        ),
        migrations.AddIndex(
            model_name="block",
            index=models.Index(
                fields=["lesson", "order"], name="lessons_blo_lesson__266462_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="block",
            constraint=models.UniqueConstraint(
                fields=("lesson", "order"), name="unique_block_order_in_lesson"
            ),
        ),
        migrations.AddIndex(
            model_name="choiceanswersubmission",
            index=models.Index(
                fields=["student", "question"], name="lessons_cho_student_0ecf77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="choiceanswersubmission",
            index=models.Index(
                fields=["student", "question", "attempt"],
                name="lessons_cho_student_c82878_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="choiceanswer",
            index=models.Index(
                fields=["question"], name="lessons_cho_questio_163068_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileanswersubmission",
            index=models.Index(
                fields=["student", "question"], name="lessons_fil_student_2ef07b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="textanswersubmission",
            index=models.Index(
                fields=["student", "question"], name="lessons_tex_student_632356_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="textanswersubmission",
            index=models.Index(
                fields=["student", "question", "attempt"],
                name="lessons_tex_student_ec858d_idx",
            ),
        ),
    ]
