# Generated by Django 6.0.4 on 2026-04-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="block",
            name="unique_block_order_in_lesson",
        ),
        migrations.RemoveConstraint(
            model_name="lesson",
            name="unique_lesson_order_in_course",
        ),
    ]
