# Generated by Django 6.0.4 on 2026-05-27 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_remove_block_unique_block_order_in_lesson_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="detail_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/courses/details/",
                verbose_name="Фото для страницы курса",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="enrollment_code",
            field=models.CharField(
                blank=True,
                help_text="Оставьте пустым, чтобы студенты записывались сразу.",
                max_length=50,
                verbose_name="Кодовое слово для записи",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="images/courses/covers/", verbose_name="Обложка"
            ),
        ),
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("approved", "Записан"),
                            ("rejected", "Отклонена"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Заявка отправлена"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="lessons.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_enrollments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на курс",
                "verbose_name_plural": "Записи на курсы",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["course", "status"],
                        name="lessons_cou_course__5ffcd2_idx",
                    ),
                    models.Index(
                        fields=["student", "status"],
                        name="lessons_cou_student_4c392a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course", "student"), name="unique_course_enrollment"
                    )
                ],
            },
        ),
    ]
