# Generated by Django 6.0.4 on 2026-05-27 19:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_course_detail_image_course_enrollment_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/certificates/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "is_completion_certificate",
                    models.BooleanField(
                        default=False, verbose_name="Выдается за прохождение курса"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_templates",
                        to="lessons.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сертификат курса",
                "verbose_name_plural": "Сертификаты курсов",
                "ordering": ["-is_completion_certificate", "title"],
            },
        ),
        migrations.CreateModel(
            name="CourseCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Завершен"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="lessons.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_completions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Завершение курса",
                "verbose_name_plural": "Завершения курсов",
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Завершен"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="lessons.lesson",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс урока",
                "verbose_name_plural": "Прогресс уроков",
            },
        ),
        migrations.CreateModel(
            name="StudentCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/student_certificates/",
                        verbose_name="Изображение",
                    ),
                ),
                ("is_completion_certificate", models.BooleanField(default=False)),
                (
                    "issued_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Выдан"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_certificates",
                        to="lessons.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_certificates",
                        to="lessons.certificatetemplate",
                        verbose_name="Шаблон сертификата",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сертификат студента",
                "verbose_name_plural": "Сертификаты студентов",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="certificatetemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_completion_certificate", True)),
                fields=("course",),
                name="unique_completion_certificate_per_course",
            ),
        ),
        migrations.AddIndex(
            model_name="coursecompletion",
            index=models.Index(
                fields=["student", "course"], name="lessons_cou_student_c59f6a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecompletion",
            constraint=models.UniqueConstraint(
                fields=("course", "student"), name="unique_course_completion"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(
                fields=["student", "lesson"], name="lessons_les_student_69e10b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonprogress",
            constraint=models.UniqueConstraint(
                fields=("lesson", "student"), name="unique_lesson_progress"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentcertificate",
            constraint=models.UniqueConstraint(
                fields=("template", "student"),
                name="unique_student_certificate_template",
            ),
        ),
    ]
