# Generated by Django 6.0.4 on 2026-05-30 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0006_student_groups_lesson_study_time"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="lessonstudytime",
            new_name="lessons_les_student_833c5d_idx",
            old_name="lessons_les_student_lesson_time_idx",
        ),
    ]
